### ISSUE TITLE
More informative README

### ISSUE THREAD

**Issue by boxleytw** [jivagoalves/gilded-rose#1]
It'd be nice hitting a project like this to read a few more things:
- This is a Kotlin project
- A brief one-liner or two on what the goals of _Gilded Rose_ are
- Tips, hints, gotchas you encountered working through the Kata (basically, coaching type stuff)
- Some badges. Everyone loves badges! :) At a minimum, at least a build status badge so folks immediately that the project is ready to clone

**Comment by jivagoalves** [comment]
Hey @boxleytw , I updated the README. Thanks for the feedback! 🙏
